Revert "[ ci, experim ] Make every test empty"
This reverts commit 7eea1decd1318530fd0bdf6f3f8d0e68020de49f.

diff --git a/tests/base/system_info001/run b/tests/base/system_info001/run
--- a/tests/base/system_info001/run
+++ b/tests/base/system_info001/run
@@ -1,1 +1,12 @@
 . ../../testutils.sh
+
+rm -f expected
+
+if ! NProcs=$(nproc || sysctl -n hw.ncpu) 2>/dev/null; then
+  echo "Command 'nproc' not found." >&2
+  exit 1
+fi
+
+echo "$NProcs processors" > expected
+
+run NumProcessors.idr
